select * from customer limit 20

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM customer
  );

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, 
ROUND(AVG(purchase_amount))
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(Purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM (
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS segmented_customers
GROUP BY customer_segment
ORDER BY customer_count DESC;

-- Q8. What are the top 3 most purchased products within each category?
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM (
    SELECT
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC, item_purchased
        ) AS item_rank,
        category,
        item_purchased,
        COUNT(*) AS total_orders
    FROM customer
    GROUP BY category, item_purchased
) ranked_items
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS repeat_buyer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyer_count DESC;

-- Q10. What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM (
    SELECT
        purchase_amount,
        CASE
            WHEN age BETWEEN 18 AND 25 THEN 'Young Adult'
            WHEN age BETWEEN 26 AND 35 THEN 'Adult'
            WHEN age BETWEEN 36 AND 50 THEN 'Middle-aged'
            ELSE 'Senior'
        END AS age_group
    FROM customer
) AS age_groups
GROUP BY age_group
ORDER BY total_revenue DESC;
