select * from customer limit 20

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
-- The results show that male customers generated significantly higher total revenue than female customers in this dataset.


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >- (select AVG(purchase_amount) from customer)
-- The results show that out of 3,900 customers, 1.677 spent more than the average purchase while still using a discount.

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5
-- The results show that Gloves, Sandals, Boots, Hats, and Skirts ranked as the top 5, in that order.

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, 
ROUND(AVG(purchase_amount))
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type
-- The results show very little difference, with standard being $58 and express being $60.

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(Purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;
-- The results show the average spend is virtually identical for subscribers and non-subscribers alike.

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND (100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
-- The results show the top 5 being; Hats, Sneakers, Coats, Sweaters, and Pants, in that order.

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment
-- The results show that the majority are loyal, 3,116, with 83 new and 701 returning customers.

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
-- The results show that the top 3 spots are all accessories, followed by clothing for the next 3 spots.

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
-- The results show 2,518 with no subscription status and 958 with subscription status.  So the anser to the question is no.


-- Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
-- The results show that young aduts lead with 62,143 in revenue, followed by middle-aged at 59,197 in revenue.  The tevenue for each age class is very similar to each other.


-- Q11. What is the revenue by category?
SELECT 
    category,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY category
ORDER BY total_revenue DESC;
-- The results show that clothing comes in 1st with $104,264 in total revenue, followed by Accessories at $74,200.

-- Q12. What is the average spend by age group and subscription
SELECT 
    age_group,
    subscription_status,
    ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer
GROUP BY age_group, subscription_status
ORDER BY age_group, avg_spend DESC;
-- The results show that the difference between the average spend, across age groups, is negligible.

